---
os: linux
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
  - "# See https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f for an example of how this was used"
  - "# Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
  - '[ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION'
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests release
rvm:
  - 2.5.8
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
jobs:
  fast_finish: true
  include:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.9
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.8
      stage: spec
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
    - chat.freenode.org#voxpupuli-notifications
  webhooks: https://voxpupu.li/incoming/travis
deploy:
  provider: puppetforge
  username: puppet
  password:
    secure: "AvnU2Qn4NqAlGCVjq3JviMLA9ci+jS7N6w60UaKX+6RUu+wIj0QLdVVl4HLohyFje7o+dvkJTL0IOS2tDP+O39DzrXzSf3bUXzfab6IIQ4vbgHAB14h+kgPQ7XBMXedgYYoZqiFhjzXb9mQYROdq2f3zz5v2NhKYeH/Dyr8m3FaCgsllUEbECQDnhNIN5m9fdx7IfxOStVygLA+TyONhjUN/aJs2NLw22au2Te7hi5eBypMlPDzK8kck0GeM7TzsKnW7iyM5/5nsitgwiOzO59f540MQGMsaU7846rQS0E10Gv4SgYmYgOx4PP2Jidpp2zO0UMZGjlKG7/SAfxMuPXh5Ovxoy9cmlD3AlNQCMjvEzJTobgutJfIuCOLDZxMzdAYAKB2yn0FWyFp4Jr7Uo7ZCc9CMmiYiKfzLhdlHbvSLccNVt8S9E5jy2L//JADho/SJLG15qCkWVrdIrQIR1LpCbACfYhoxTTcrFBCW+sU55QMPYe7eDumIl4wcMl4yCcbuzxoq+FJOcqkliS4q1uULstiJLQf70Fcr+xR4tyz2MNXlOcQheRa+2oTcg6chRd01iSf2CvhfHSkFGGZHmwwZwexKmVi4Renk/nR1Ayml937qKNnxSQI03y4J8iPrR5Tr1V8u07zgu6o2Dh94PQoaTgV1YsYK+rZDMafzx18="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
